### ISSUE TITLE
Add linting configuration to the repo and force it on commit

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/rmb_sdk_ts#4]

**Comment by AhmedHanafy725** [comment]
didn't see a linting workflow running 

![image](https://user-images.githubusercontent.com/41957921/227785251-2808b7c7-148b-4713-a5da-3ba69fab7595.png)

**Comment by A-Harby** [comment]
Verified from workflow from last merge.
![image](https://user-images.githubusercontent.com/109473873/231149353-d1baef79-2063-4793-bd1f-c543949f5a99.png)
